[tools]
node = "22.20.0"
java = "jdk1.8.0_401.jdk"
python = "3.8.20"
go = "1.22.9"
pnpm = "10.26.0"
yarn = "4.12.0"

fd = "latest"
rg = "latest"
usage = "latest"
uv = "latest"
eza = "latest"
duf = "latest"
yazi = "latest"
fzf = "latest"
jq = "latest"
golangci-lint = "latest"
gofumpt = "latest"
# gopls = "latest"
"ubi:goreleaser/goreleaser" = "latest"
bun = "1.3.12"
zig = "0.15.2"
zls = "latest"
lazygit = "latest"
yq = "latest"
lsd = "latest"

[env]
# _.python.venv = { path = ".venv", create = true, uv_create_args = ['--seed'] }

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
# python.uv_venv_auto = true
